development:
  access_key_id: 'AKIAJDCD46LYXKNBDTKQ'
  secret_access_key: ''
  bucket: 'votingmodule'

test:
  access_key_id: 'AKIAJDCD46LYXKNBDTKQ'
  secret_access_key: ''
  bucket: 'votingmodule'

production:
  access_key_id: 'AKIAJDCD46LYXKNBDTKQ'
  secret_access_key: ''
  bucket: 'votingmodule'
