development:
  access_key_id: 'AKIAJDCD46LYXKNBDTKQ'
  secret_access_key: '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'
  bucket: 'votingmodule'

test:
  access_key_id: 'AKIAJDCD46LYXKNBDTKQ'
  secret_access_key: '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'
  bucket: 'votingmodule'

production:
  access_key_id: 'AKIAJDCD46LYXKNBDTKQ'
  secret_access_key: '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'
  bucket: 'votingmodule'
