require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DelegatesController do

  def mock_delegate(stubs={})
    @mock_delegate ||= mock_model(Delegate, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all delegates as @delegates" do
      Delegate.stub(:all) { [mock_delegate] }
      get :index
      assigns(:delegates).should eq([mock_delegate])
    end
  end

  describe "GET show" do
    it "assigns the requested delegate as @delegate" do
      Delegate.stub(:find).with("37") { mock_delegate }
      get :show, :id => "37"
      assigns(:delegate).should be(mock_delegate)
    end
  end

  describe "GET new" do
    it "assigns a new delegate as @delegate" do
      Delegate.stub(:new) { mock_delegate }
      get :new
      assigns(:delegate).should be(mock_delegate)
    end
  end

  describe "GET edit" do
    it "assigns the requested delegate as @delegate" do
      Delegate.stub(:find).with("37") { mock_delegate }
      get :edit, :id => "37"
      assigns(:delegate).should be(mock_delegate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created delegate as @delegate" do
        Delegate.stub(:new).with({'these' => 'params'}) { mock_delegate(:save => true) }
        post :create, :delegate => {'these' => 'params'}
        assigns(:delegate).should be(mock_delegate)
      end

      it "redirects to the created delegate" do
        Delegate.stub(:new) { mock_delegate(:save => true) }
        post :create, :delegate => {}
        response.should redirect_to(delegate_url(mock_delegate))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved delegate as @delegate" do
        Delegate.stub(:new).with({'these' => 'params'}) { mock_delegate(:save => false) }
        post :create, :delegate => {'these' => 'params'}
        assigns(:delegate).should be(mock_delegate)
      end

      it "re-renders the 'new' template" do
        Delegate.stub(:new) { mock_delegate(:save => false) }
        post :create, :delegate => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested delegate" do
        Delegate.stub(:find).with("37") { mock_delegate }
        mock_delegate.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :delegate => {'these' => 'params'}
      end

      it "assigns the requested delegate as @delegate" do
        Delegate.stub(:find) { mock_delegate(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:delegate).should be(mock_delegate)
      end

      it "redirects to the delegate" do
        Delegate.stub(:find) { mock_delegate(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(delegate_url(mock_delegate))
      end
    end

    describe "with invalid params" do
      it "assigns the delegate as @delegate" do
        Delegate.stub(:find) { mock_delegate(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:delegate).should be(mock_delegate)
      end

      it "re-renders the 'edit' template" do
        Delegate.stub(:find) { mock_delegate(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested delegate" do
      Delegate.stub(:find).with("37") { mock_delegate }
      mock_delegate.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the delegates list" do
      Delegate.stub(:find) { mock_delegate }
      delete :destroy, :id => "1"
      response.should redirect_to(delegates_url)
    end
  end

end
