require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DelegationsController do

  def mock_delegation(stubs={})
    @mock_delegation ||= mock_model(Delegation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all delegations as @delegations" do
      Delegation.stub(:all) { [mock_delegation] }
      get :index
      assigns(:delegations).should eq([mock_delegation])
    end
  end

  describe "GET show" do
    it "assigns the requested delegation as @delegation" do
      Delegation.stub(:find).with("37") { mock_delegation }
      get :show, :id => "37"
      assigns(:delegation).should be(mock_delegation)
    end
  end

  describe "GET new" do
    it "assigns a new delegation as @delegation" do
      Delegation.stub(:new) { mock_delegation }
      get :new
      assigns(:delegation).should be(mock_delegation)
    end
  end

  describe "GET edit" do
    it "assigns the requested delegation as @delegation" do
      Delegation.stub(:find).with("37") { mock_delegation }
      get :edit, :id => "37"
      assigns(:delegation).should be(mock_delegation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created delegation as @delegation" do
        Delegation.stub(:new).with({'these' => 'params'}) { mock_delegation(:save => true) }
        post :create, :delegation => {'these' => 'params'}
        assigns(:delegation).should be(mock_delegation)
      end

      it "redirects to the created delegation" do
        Delegation.stub(:new) { mock_delegation(:save => true) }
        post :create, :delegation => {}
        response.should redirect_to(delegation_url(mock_delegation))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved delegation as @delegation" do
        Delegation.stub(:new).with({'these' => 'params'}) { mock_delegation(:save => false) }
        post :create, :delegation => {'these' => 'params'}
        assigns(:delegation).should be(mock_delegation)
      end

      it "re-renders the 'new' template" do
        Delegation.stub(:new) { mock_delegation(:save => false) }
        post :create, :delegation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested delegation" do
        Delegation.stub(:find).with("37") { mock_delegation }
        mock_delegation.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :delegation => {'these' => 'params'}
      end

      it "assigns the requested delegation as @delegation" do
        Delegation.stub(:find) { mock_delegation(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:delegation).should be(mock_delegation)
      end

      it "redirects to the delegation" do
        Delegation.stub(:find) { mock_delegation(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(delegation_url(mock_delegation))
      end
    end

    describe "with invalid params" do
      it "assigns the delegation as @delegation" do
        Delegation.stub(:find) { mock_delegation(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:delegation).should be(mock_delegation)
      end

      it "re-renders the 'edit' template" do
        Delegation.stub(:find) { mock_delegation(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested delegation" do
      Delegation.stub(:find).with("37") { mock_delegation }
      mock_delegation.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the delegations list" do
      Delegation.stub(:find) { mock_delegation }
      delete :destroy, :id => "1"
      response.should redirect_to(delegations_url)
    end
  end

end
