require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe InitiativesController do

  def mock_initiative(stubs={})
    @mock_initiative ||= mock_model(Initiative, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all initiatives as @initiatives" do
      Initiative.stub(:all) { [mock_initiative] }
      get :index
      assigns(:initiatives).should eq([mock_initiative])
    end
  end

  describe "GET show" do
    it "assigns the requested initiative as @initiative" do
      Initiative.stub(:find).with("37") { mock_initiative }
      get :show, :id => "37"
      assigns(:initiative).should be(mock_initiative)
    end
  end

  describe "GET new" do
    it "assigns a new initiative as @initiative" do
      Initiative.stub(:new) { mock_initiative }
      get :new
      assigns(:initiative).should be(mock_initiative)
    end
  end

  describe "GET edit" do
    it "assigns the requested initiative as @initiative" do
      Initiative.stub(:find).with("37") { mock_initiative }
      get :edit, :id => "37"
      assigns(:initiative).should be(mock_initiative)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created initiative as @initiative" do
        Initiative.stub(:new).with({'these' => 'params'}) { mock_initiative(:save => true) }
        post :create, :initiative => {'these' => 'params'}
        assigns(:initiative).should be(mock_initiative)
      end

      it "redirects to the created initiative" do
        Initiative.stub(:new) { mock_initiative(:save => true) }
        post :create, :initiative => {}
        response.should redirect_to(initiative_url(mock_initiative))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved initiative as @initiative" do
        Initiative.stub(:new).with({'these' => 'params'}) { mock_initiative(:save => false) }
        post :create, :initiative => {'these' => 'params'}
        assigns(:initiative).should be(mock_initiative)
      end

      it "re-renders the 'new' template" do
        Initiative.stub(:new) { mock_initiative(:save => false) }
        post :create, :initiative => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested initiative" do
        Initiative.stub(:find).with("37") { mock_initiative }
        mock_initiative.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :initiative => {'these' => 'params'}
      end

      it "assigns the requested initiative as @initiative" do
        Initiative.stub(:find) { mock_initiative(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:initiative).should be(mock_initiative)
      end

      it "redirects to the initiative" do
        Initiative.stub(:find) { mock_initiative(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(initiative_url(mock_initiative))
      end
    end

    describe "with invalid params" do
      it "assigns the initiative as @initiative" do
        Initiative.stub(:find) { mock_initiative(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:initiative).should be(mock_initiative)
      end

      it "re-renders the 'edit' template" do
        Initiative.stub(:find) { mock_initiative(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested initiative" do
      Initiative.stub(:find).with("37") { mock_initiative }
      mock_initiative.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the initiatives list" do
      Initiative.stub(:find) { mock_initiative }
      delete :destroy, :id => "1"
      response.should redirect_to(initiatives_url)
    end
  end

end
