require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ReferendumsController do

  def mock_referendum(stubs={})
    @mock_referendum ||= mock_model(Referendum, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all referendums as @referendums" do
      Referendum.stub(:all) { [mock_referendum] }
      get :index
      assigns(:referendums).should eq([mock_referendum])
    end
  end

  describe "GET show" do
    it "assigns the requested referendum as @referendum" do
      Referendum.stub(:find).with("37") { mock_referendum }
      get :show, :id => "37"
      assigns(:referendum).should be(mock_referendum)
    end
  end

  describe "GET new" do
    it "assigns a new referendum as @referendum" do
      Referendum.stub(:new) { mock_referendum }
      get :new
      assigns(:referendum).should be(mock_referendum)
    end
  end

  describe "GET edit" do
    it "assigns the requested referendum as @referendum" do
      Referendum.stub(:find).with("37") { mock_referendum }
      get :edit, :id => "37"
      assigns(:referendum).should be(mock_referendum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created referendum as @referendum" do
        Referendum.stub(:new).with({'these' => 'params'}) { mock_referendum(:save => true) }
        post :create, :referendum => {'these' => 'params'}
        assigns(:referendum).should be(mock_referendum)
      end

      it "redirects to the created referendum" do
        Referendum.stub(:new) { mock_referendum(:save => true) }
        post :create, :referendum => {}
        response.should redirect_to(referendum_url(mock_referendum))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved referendum as @referendum" do
        Referendum.stub(:new).with({'these' => 'params'}) { mock_referendum(:save => false) }
        post :create, :referendum => {'these' => 'params'}
        assigns(:referendum).should be(mock_referendum)
      end

      it "re-renders the 'new' template" do
        Referendum.stub(:new) { mock_referendum(:save => false) }
        post :create, :referendum => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested referendum" do
        Referendum.stub(:find).with("37") { mock_referendum }
        mock_referendum.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :referendum => {'these' => 'params'}
      end

      it "assigns the requested referendum as @referendum" do
        Referendum.stub(:find) { mock_referendum(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:referendum).should be(mock_referendum)
      end

      it "redirects to the referendum" do
        Referendum.stub(:find) { mock_referendum(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(referendum_url(mock_referendum))
      end
    end

    describe "with invalid params" do
      it "assigns the referendum as @referendum" do
        Referendum.stub(:find) { mock_referendum(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:referendum).should be(mock_referendum)
      end

      it "re-renders the 'edit' template" do
        Referendum.stub(:find) { mock_referendum(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested referendum" do
      Referendum.stub(:find).with("37") { mock_referendum }
      mock_referendum.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the referendums list" do
      Referendum.stub(:find) { mock_referendum }
      delete :destroy, :id => "1"
      response.should redirect_to(referendums_url)
    end
  end

end
